In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("Sample data.csv")

df

   transaction_id  customer_name                 email  amount      date
0            1001       John Doe       j.doe@email.com   150.0  1/1/2024
1            1002     Jane Smith      jane.s@email.com   200.5  1/2/2024
2            1001       John Doe       j.doe@email.com   150.0  1/1/2024
3            1003    Alex Rivera                   NaN    45.0  1/3/2024
4            1004   Sarah Connor      s.connor@sky.net   300.0  1/4/2024
5            1005  Michael Scott    m.scott@dunder.com     NaN  1/5/2024
6            1002     Jane Smith      jane.s@email.com   200.5  1/2/2024
7            1006   Ellen Ripley  e.ripley@weyland.com   500.0  1/6/2024
8            1007            NaN     unknown@email.com   120.0  1/7/2024
9            1008    Bruce Wayne       bruce@wayne.com  1000.0  1/8/2024

In [3]:
df.dtypes

transaction_id      int64
customer_name         str
email                 str
amount            float64
date                  str
dtype: object

In [4]:
columns = df.columns
columns

Index(['transaction_id', 'customer_name', 'email', 'amount', 'date'], dtype='str')

In [5]:
column_with_null = df.columns[df.isnull().any()]
column_with_null

Index(['customer_name', 'email', 'amount'], dtype='str')

In [6]:
df.isna().sum()

transaction_id    0
customer_name     1
email             1
amount            1
date              0
dtype: int64

Handling null values

In [10]:
row_with_null = df[df.isnull().any(axis=1)]

row_with_null

   transaction_id  customer_name               email  amount      date
3            1003    Alex Rivera                 NaN    45.0  1/3/2024
5            1005  Michael Scott  m.scott@dunder.com     NaN  1/5/2024
8            1007            NaN   unknown@email.com   120.0  1/7/2024

In [11]:
row_with_no_null = df[~df.isnull().any(axis=1)]

row_with_no_null

   transaction_id customer_name                 email  amount      date
0            1001      John Doe       j.doe@email.com   150.0  1/1/2024
1            1002    Jane Smith      jane.s@email.com   200.5  1/2/2024
2            1001      John Doe       j.doe@email.com   150.0  1/1/2024
4            1004  Sarah Connor      s.connor@sky.net   300.0  1/4/2024
6            1002    Jane Smith      jane.s@email.com   200.5  1/2/2024
7            1006  Ellen Ripley  e.ripley@weyland.com   500.0  1/6/2024
9            1008   Bruce Wayne       bruce@wayne.com  1000.0  1/8/2024

Handling Duplicates

In [12]:
row_with_no_null

   transaction_id customer_name                 email  amount      date
0            1001      John Doe       j.doe@email.com   150.0  1/1/2024
1            1002    Jane Smith      jane.s@email.com   200.5  1/2/2024
2            1001      John Doe       j.doe@email.com   150.0  1/1/2024
4            1004  Sarah Connor      s.connor@sky.net   300.0  1/4/2024
6            1002    Jane Smith      jane.s@email.com   200.5  1/2/2024
7            1006  Ellen Ripley  e.ripley@weyland.com   500.0  1/6/2024
9            1008   Bruce Wayne       bruce@wayne.com  1000.0  1/8/2024

In [13]:
duplicated = row_with_no_null.duplicated()

duplicated

0    False
1    False
2     True
4    False
6     True
7    False
9    False
dtype: bool

In [15]:
duplicate_rows = row_with_no_null[row_with_no_null.duplicated()]

duplicate_rows

   transaction_id customer_name             email  amount      date
2            1001      John Doe   j.doe@email.com   150.0  1/1/2024
6            1002    Jane Smith  jane.s@email.com   200.5  1/2/2024

In [19]:
no_duplicate_data = row_with_no_null[~row_with_no_null.duplicated()]

no_duplicate_data

   transaction_id customer_name                 email  amount      date
0            1001      John Doe       j.doe@email.com   150.0  1/1/2024
1            1002    Jane Smith      jane.s@email.com   200.5  1/2/2024
4            1004  Sarah Connor      s.connor@sky.net   300.0  1/4/2024
7            1006  Ellen Ripley  e.ripley@weyland.com   500.0  1/6/2024
9            1008   Bruce Wayne       bruce@wayne.com  1000.0  1/8/2024

In [ ]:
clean_data = no_dupli

   transaction_id  customer_name                 email  amount      date
0            1001       John Doe       j.doe@email.com   150.0  1/1/2024
1            1002     Jane Smith      jane.s@email.com   200.5  1/2/2024
2            1001       John Doe       j.doe@email.com   150.0  1/1/2024
3            1003    Alex Rivera                   NaN    45.0  1/3/2024
4            1004   Sarah Connor      s.connor@sky.net   300.0  1/4/2024
5            1005  Michael Scott    m.scott@dunder.com     NaN  1/5/2024
6            1002     Jane Smith      jane.s@email.com   200.5  1/2/2024
7            1006   Ellen Ripley  e.ripley@weyland.com   500.0  1/6/2024
8            1007            NaN     unknown@email.com   120.0  1/7/2024
9            1008    Bruce Wayne       bruce@wayne.com  1000.0  1/8/2024